<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="KinhThanhCongGiao.Model">
      <HintPath>..\..\..\kinh-thanh-model\KinhThanhCongGiao.Model\KinhThanhCongGiao.Model\bin\Debug\net8.0\KinhThanhCongGiao.Model.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Serilog" Version="4.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KinhThanhCongGiao.Application\KinhThanhCongGiao.Application.csproj" />
  </ItemGroup>

</Project>
