name: ci-cd

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up .NET 6
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: "6.0.x"
        
      - name: Restore Dependencies
        run: dotnet restore
      
      - name: Build app 
        run: dotnet build  -c Release --no-restore
